### ISSUE TITLE
Support for VS2022 64bit versions

### ISSUE THREAD

**Issue by Nir1812** [rog1039/Rogero.RegionHighlights#10]
You have to update the manifest in order to support 64 bit too:

```
<Installation>
    <InstallationTarget Version="[11.0,18.0)" Id="Microsoft.VisualStudio.Pro">
        <ProductArchitecture>x86</ProductArchitecture>
    </InstallationTarget>
    <InstallationTarget Version="[11.0,18.0)" Id="Microsoft.VisualStudio.Community">
        <ProductArchitecture>x86</ProductArchitecture>
    </InstallationTarget>
    <InstallationTarget Version="[11.0,18.0)" Id="Microsoft.VisualStudio.Enterprise">
        <ProductArchitecture>x86</ProductArchitecture>
    </InstallationTarget>
    <InstallationTarget Version="[17.0,18.0)" Id="Microsoft.VisualStudio.Pro">
        <ProductArchitecture>amd64</ProductArchitecture>
    </InstallationTarget>
    <InstallationTarget Version="[17.0,18.0)" Id="Microsoft.VisualStudio.Community">
        <ProductArchitecture>amd64</ProductArchitecture>
    </InstallationTarget>
    <InstallationTarget Version="[17.0,18.0)" Id="Microsoft.VisualStudio.Enterprise">
        <ProductArchitecture>amd64</ProductArchitecture>
    </InstallationTarget>
</Installation>

```

**Comment by rog1039** [comment]
Hi!
I don't completely understand the issue. The manifest in the repo supports 64-bit I believe. It looks similar to what you just posted but has only 17.0) for the x86 targets. I don't think x86 versions of 2022 exist? Could you explain more or let me know if I am totally missing something?
Thanks,
Paul

**Comment by Nir1812** [comment]
Actually, I think the missing line in the manifest is this one:
`<ProductArchitecture>amd64</ProductArchitecture>`

**Comment by rog1039** [comment]
Isn't it listed in the bottom three InstallationTarget groups?

**Comment by Nir1812** [comment]
Not in the package you download... I had to add those manually for it to install on my VS2022...
I've downloaded the package from within VS2022 extensions manager... Maybe it has older version?

**Comment by rog1039** [comment]
I see what you mean. I'll push a new extension to the marketplace shortly.

**Comment by Nir1812** [comment]
I've checked the package you download from this link, and it is missing these keys...

[https://marketplace.visualstudio.com/items?itemName=PaulRogero.RegionHighlights](https://marketplace.visualstudio.com/items?itemName=PaulRogero.RegionHighlights)

**Comment by rog1039** [comment]
Marketplace version has been updated. Let me know if that takes care of the issue. Thanks.

**Comment by Nir1812** [comment]
Yep. Now it's fine.

**Comment by rog1039** [comment]
Good to hear!
